name: mafqoodi_mobile
description: "Mafqoodi Flutter client"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.6.0
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  easy_localization: ^3.0.8
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
